name             'ncloud'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures nclouds'
long_description 'Installs/Configures nclouds'
version          '0.1.0'
depends 'ncloud'
