name 'ncloud-etcd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ncloud-etcd'
long_description 'Installs/Configures ncloud-etcd'
version '0.0.1'

depends 'etcd'
depends 'confd'
depends 'build-essential'
